/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients 
{
    /// <summary>
    /// The Air Quality Index is a measure of how clean or polluted air is. From min, good quality, to high, low quality.
     /// The range of AQI may vary between countries (https://en.wikipedia.org/wiki/Air_quality_index).
    /// Implements a client for the Air Quality Index service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/airqualityindex/" />
    public partial class AirQualityIndexClient : SensorClient
    {
        public AirQualityIndexClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.AirQualityIndex)
        {
        }

        /// <summary>
        /// Reads the <c>aqi_index</c> register value.
        /// Air quality index, typically refreshed every second., _: AQI
        /// </summary>
        public float AqiIndex
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)AirQualityIndexReg.AqiIndex, AirQualityIndexRegPack.AqiIndex);
            }
        }

        /// <summary>
        /// Tries to read the <c>aqi_index_error</c> register value.
        /// Error on the AQI measure., _: AQI
        /// </summary>
        bool TryGetAqiIndexError(out float value)
        {
            object[] values;
            if (this.TryGetRegisterValues((ushort)AirQualityIndexReg.AqiIndexError, AirQualityIndexRegPack.AqiIndexError, out values)) 
            {
                value = (float)values[0];
                return true;
            }
            else
            {
                value = default(float);
                return false;
            }
        }

        /// <summary>
        /// Reads the <c>min_aqi_index</c> register value.
        /// Minimum AQI reading, representing a good air quality. Typically 0., _: AQI
        /// </summary>
        public float MinAqiIndex
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)AirQualityIndexReg.MinAqiIndex, AirQualityIndexRegPack.MinAqiIndex);
            }
        }

        /// <summary>
        /// Reads the <c>max_aqi_index</c> register value.
        /// Maximum AQI reading, representing a very poor air quality., _: AQI
        /// </summary>
        public float MaxAqiIndex
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)AirQualityIndexReg.MaxAqiIndex, AirQualityIndexRegPack.MaxAqiIndex);
            }
        }


    }
}