/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients {

    /// <summary>
    /// Health and diagnostics information about the Azure Iot Hub connection.
    /// Implements a client for the Azure IoT Hub Health service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/azureiothubhealth/" />
    public partial class AzureIotHubHealthClient : Client
    {
        public AzureIotHubHealthClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.AzureIotHubHealth)
        {
        }

        /// <summary>
        /// Tries to read the <c>hub_name</c> register value.
        /// Something like `my-iot-hub.azure-devices.net` if available., 
        /// </summary>
        bool TryGetHubName(out string value)
        {
            object[] values;
            if (this.TryGetRegisterValues((ushort)AzureIotHubHealthReg.HubName, AzureIotHubHealthRegPack.HubName, out values)) 
            {
                value = (string)values[0];
                return true;
            }
            else
            {
                value = default(string);
                return false;
            }
        }

        /// <summary>
        /// Tries to read the <c>hub_device_id</c> register value.
        /// Device identifier in Azure Iot Hub if available., 
        /// </summary>
        bool TryGetHubDeviceId(out string value)
        {
            object[] values;
            if (this.TryGetRegisterValues((ushort)AzureIotHubHealthReg.HubDeviceId, AzureIotHubHealthRegPack.HubDeviceId, out values)) 
            {
                value = (string)values[0];
                return true;
            }
            else
            {
                value = default(string);
                return false;
            }
        }

        /// <summary>
        /// Reads the <c>connection_status</c> register value.
        /// Indicates the status of connection. A message beyond the [0..3] range represents an HTTP error code., 
        /// </summary>
        public AzureIotHubHealthConnectionStatus ConnectionStatus
        {
            get
            {
                return (AzureIotHubHealthConnectionStatus)this.GetRegisterValue((ushort)AzureIotHubHealthReg.ConnectionStatus, AzureIotHubHealthRegPack.ConnectionStatus);
            }
        }

        /// <summary>
        /// Raised when the connection status changes
        /// </summary>
        public event ClientEventHandler ConnectionStatusChange
        {
            add
            {
                this.AddEvent((ushort)AzureIotHubHealthEvent.ConnectionStatusChange, value);
            }
            remove
            {
                this.RemoveEvent((ushort)AzureIotHubHealthEvent.ConnectionStatusChange, value);
            }
        }

        /// <summary>
        /// Raised when a message has been sent to the hub.
        /// </summary>
        public event ClientEventHandler MessageSent
        {
            add
            {
                this.AddEvent((ushort)AzureIotHubHealthEvent.MessageSent, value);
            }
            remove
            {
                this.RemoveEvent((ushort)AzureIotHubHealthEvent.MessageSent, value);
            }
        }


        
        /// <summary>
        /// Starts a connection to the IoT hub service
        /// </summary>
        public void Connect()
        {
            this.SendCmd((ushort)AzureIotHubHealthCmd.Connect);
        }

        
        /// <summary>
        /// Starts disconnecting from the IoT hub service
        /// </summary>
        public void Disconnect()
        {
            this.SendCmd((ushort)AzureIotHubHealthCmd.Disconnect);
        }

    }
}