/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac {

    /// <summary>
    /// A sensor measuring air pressure of outside environment.
    /// Implements a client for the Barometer service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/barometer/" />
    public partial class BarometerClient : SensorClient
    {
        public BarometerClient(JDBus bus, string name)
            : base(bus, ServiceClasses.Barometer, name)
        {
        }

        /// <summary>
        /// The air pressure., _: hPa
        /// </summary>
        public float Pressure
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)BarometerReg.Pressure, BarometerRegPack.Pressure, 1);
            }
        }

        /// <summary>
        /// (Optional) The real pressure is between `pressure - pressure_error` and `pressure + pressure_error`., _: hPa
        /// </summary>
        public float PressureError
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)BarometerReg.PressureError, BarometerRegPack.PressureError, 1);
            }
        }


    }
}