/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients {

    /// <summary>
    /// A configuration service for a capacitive push-button.
    /// Implements a client for the Capacitive Button service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/capacitivebutton/" />
    public partial class CapacitiveButtonClient : Client
    {
        public CapacitiveButtonClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.CapacitiveButton)
        {
        }

        /// <summary>
        /// Indicates the threshold for ``up`` events., _: /
        /// </summary>
        public float Threshold
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)CapacitiveButtonReg.Threshold, CapacitiveButtonRegPack.Threshold);
            }
            set
            {
                
                this.SetRegisterValue((ushort)CapacitiveButtonReg.Threshold, CapacitiveButtonRegPack.Threshold, value);
            }

        }


        /// <summary>
        /// Request to calibrate the capactive. When calibration is requested, the device expects that no object is touching the button. 
        /// The report indicates the calibration is done.
        /// </summary>
        public void Calibrate()
        {
            this.SendCmd((ushort)CapacitiveButtonCmd.Calibrate);
        }

    }
}