/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients 
{
    /// <summary>
    /// Senses RGB colors
    /// Implements a client for the Color service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/color/" />
    public partial class ColorClient : SensorClient
    {
        public ColorClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.Color)
        {
        }

        /// <summary>
        /// Reads the <c>color</c> register value.
        /// Detected color in the RGB color space., red: /,green: /,blue: /
        /// </summary>
        public object[] /*(float, float, float)*/ Color
        {
            get
            {
                return (object[] /*(float, float, float)*/)this.GetRegisterValues((ushort)ColorReg.Color, ColorRegPack.Color);
            }
        }


    }
}