/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac {

    /// <summary>
    /// Senses RGB colors
    /// Implements a client for the Color service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/color/" />
    public partial class ColorClient : SensorClient
    {
        public ColorClient(JDBus bus, string name)
            : base(bus, (ushort)ColorConstants.ServiceClass, name)
        {
        }

        /// <summary>
        /// Detected color in the RGB color space., red: /,green: /,blue: /
        /// </summary>
        public (float, float, float) Color
        {
            get
            {
                return ((float, float, float))this.GetRegisterValue((ushort)ColorReg.Color, ColorRegPack.Color, 1);
            }
        }


    }
}