/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients 
{
    /// <summary>
    /// A service that reports a current measurement.
    /// Implements a client for the DC Current Measurement service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/dccurrentmeasurement/" />
    public partial class DCCurrentMeasurementClient : SensorClient
    {
        public DCCurrentMeasurementClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.DCCurrentMeasurement)
        {
        }

        /// <summary>
        /// Reads the <c>measurement_name</c> register value.
        /// A string containing the net name that is being measured e.g. `POWER_DUT` or a reference e.g. `DIFF_DEV1_DEV2`. These constants can be used to identify a measurement from client code., 
        /// </summary>
        public string MeasurementName
        {
            get
            {
                return (string)this.GetRegisterValue((ushort)DCCurrentMeasurementReg.MeasurementName, DCCurrentMeasurementRegPack.MeasurementName);
            }
        }

        /// <summary>
        /// Reads the <c>measurement</c> register value.
        /// The current measurement., _: A
        /// </summary>
        public float Measurement
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)DCCurrentMeasurementReg.Measurement, DCCurrentMeasurementRegPack.Measurement);
            }
        }


    }
}