/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients 
{
    /// <summary>
    /// A service that reports a current measurement.
    /// Implements a client for the DC Current Measurement service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/dccurrentmeasurement/" />
    public partial class DcCurrentMeasurementClient : SensorClient
    {
        public DcCurrentMeasurementClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.DcCurrentMeasurement)
        {
        }

        /// <summary>
        /// Reads the <c>measurement_name</c> register value.
        /// A string containing the net name that is being measured e.g. `POWER_DUT` or a reference e.g. `DIFF_DEV1_DEV2`. These constants can be used to identify a measurement from client code., 
        /// </summary>
        public string MeasurementName
        {
            get
            {
                return (string)this.GetRegisterValue((ushort)DcCurrentMeasurementReg.MeasurementName, DcCurrentMeasurementRegPack.MeasurementName);
            }
        }

        /// <summary>
        /// Reads the <c>measurement</c> register value.
        /// The current measurement., _: A
        /// </summary>
        public float Measurement
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)DcCurrentMeasurementReg.Measurement, DcCurrentMeasurementRegPack.Measurement);
            }
        }

        /// <summary>
        /// Tries to read the <c>measurement_error</c> register value.
        /// Absolute error on the reading value., _: A
        /// </summary>
        bool TryGetMeasurementError(out float value)
        {
            object[] values;
            if (this.TryGetRegisterValues((ushort)DcCurrentMeasurementReg.MeasurementError, DcCurrentMeasurementRegPack.MeasurementError, out values)) 
            {
                value = (float)values[0];
                return true;
            }
            else
            {
                value = default(float);
                return false;
            }
        }

        /// <summary>
        /// Tries to read the <c>min_measurement</c> register value.
        /// Minimum measurable current, _: A
        /// </summary>
        bool TryGetMinMeasurement(out float value)
        {
            object[] values;
            if (this.TryGetRegisterValues((ushort)DcCurrentMeasurementReg.MinMeasurement, DcCurrentMeasurementRegPack.MinMeasurement, out values)) 
            {
                value = (float)values[0];
                return true;
            }
            else
            {
                value = default(float);
                return false;
            }
        }

        /// <summary>
        /// Tries to read the <c>max_measurement</c> register value.
        /// Maximum measurable current, _: A
        /// </summary>
        bool TryGetMaxMeasurement(out float value)
        {
            object[] values;
            if (this.TryGetRegisterValues((ushort)DcCurrentMeasurementReg.MaxMeasurement, DcCurrentMeasurementRegPack.MaxMeasurement, out values)) 
            {
                value = (float)values[0];
                return true;
            }
            else
            {
                value = default(float);
                return false;
            }
        }


    }
}