/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients 
{
    /// <summary>
    /// Conditions are synthetic services used to synchronize threads of executions of a DeviceScript VM.
    /// Implements a client for the DeviceScript Condition service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/devicescriptcondition/" />
    public partial class DeviceScriptConditionClient : Client
    {
        public DeviceScriptConditionClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.DeviceScriptCondition)
        {
        }

        /// <summary>
        /// Triggered by `signal` command.
        /// </summary>
        public event ClientEventHandler Signalled
        {
            add
            {
                this.AddEvent((ushort)DeviceScriptConditionEvent.Signalled, value);
            }
            remove
            {
                this.RemoveEvent((ushort)DeviceScriptConditionEvent.Signalled, value);
            }
        }


        
        /// <summary>
        /// Triggers a `signalled` event.
        /// </summary>
        public void Signal()
        {
            this.SendCmd((ushort)DeviceScriptConditionCmd.Signal);
        }

    }
}