/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients {

    /// <summary>
    /// A rectangular dot matrix display, made of monochrome LEDs or Braille pins.
    /// Implements a client for the Dot Matrix service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/dotmatrix/" />
    public partial class DotMatrixClient : Client
    {
        public DotMatrixClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.DotMatrix)
        {
        }

        /// <summary>
        /// Reads the <c>dots</c> register value.
        /// The state of the screen where dot on/off state is
        /// stored as a bit, column by column. The column should be byte aligned., 
        /// </summary>
        public byte[] Dots
        {
            get
            {
                return (byte[])this.GetRegisterValue((ushort)DotMatrixReg.Dots, DotMatrixRegPack.Dots);
            }
            set
            {
                
                this.SetRegisterValue((ushort)DotMatrixReg.Dots, DotMatrixRegPack.Dots, value);
            }

        }

        /// <summary>
        /// Tries to read the <c>brightness</c> register value.
        /// Reads the general brightness of the display, brightness for LEDs. `0` when the screen is off., _: /
        /// </summary>
        bool TryGetBrightness(out float value)
        {
            object[] values;
            if (this.TryGetRegisterValues((ushort)DotMatrixReg.Brightness, DotMatrixRegPack.Brightness, out values)) 
            {
                value = (float)values[0];
                return true;
            }
            else
            {
                value = default(float);
                return false;
            }
        }
        
        /// <summary>
        /// Sets the brightness value
        /// </summary>
        public void SetBrightness(float value)
        {
            this.SetRegisterValue((ushort)DotMatrixReg.Brightness, DotMatrixRegPack.Brightness, value);
        }


        /// <summary>
        /// Reads the <c>rows</c> register value.
        /// Number of rows on the screen, _: #
        /// </summary>
        public uint Rows
        {
            get
            {
                return (uint)this.GetRegisterValue((ushort)DotMatrixReg.Rows, DotMatrixRegPack.Rows);
            }
        }

        /// <summary>
        /// Reads the <c>columns</c> register value.
        /// Number of columns on the screen, _: #
        /// </summary>
        public uint Columns
        {
            get
            {
                return (uint)this.GetRegisterValue((ushort)DotMatrixReg.Columns, DotMatrixRegPack.Columns);
            }
        }

        /// <summary>
        /// Tries to read the <c>variant</c> register value.
        /// Describes the type of matrix used., 
        /// </summary>
        bool TryGetVariant(out DotMatrixVariant value)
        {
            object[] values;
            if (this.TryGetRegisterValues((ushort)DotMatrixReg.Variant, DotMatrixRegPack.Variant, out values)) 
            {
                value = (DotMatrixVariant)values[0];
                return true;
            }
            else
            {
                value = default(DotMatrixVariant);
                return false;
            }
        }


    }
}