/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients 
{
    /// <summary>
    /// A synchronized pair of motors.
    /// Implements a client for the Dual Motors service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/dualmotors/" />
    public partial class DualMotorsClient : Client
    {
        public DualMotorsClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.DualMotors)
        {
        }

        /// <summary>
        /// Reads the <c>speed</c> register value.
        /// Relative speed of the motors. Use positive/negative values to run the motor forwards and backwards.
        /// A speed of ``0`` while ``enabled`` acts as brake., left: /,right: /
        /// </summary>
        public object[] /*(float, float)*/ Speed
        {
            get
            {
                return (object[] /*(float, float)*/)this.GetRegisterValues((ushort)DualMotorsReg.Speed, DualMotorsRegPack.Speed);
            }
            set
            {
                
                this.Enabled = true;
                this.SetRegisterValues((ushort)DualMotorsReg.Speed, DualMotorsRegPack.Speed, value);
            }

        }

        /// <summary>
        /// Reads the <c>enabled</c> register value.
        /// Turn the power to the motors on/off., 
        /// </summary>
        public bool Enabled
        {
            get
            {
                return (bool)this.GetRegisterValueAsBool((ushort)DualMotorsReg.Enabled, DualMotorsRegPack.Enabled);
            }
            set
            {
                
                this.SetRegisterValue((ushort)DualMotorsReg.Enabled, DualMotorsRegPack.Enabled, value);
            }

        }

        /// <summary>
        /// Tries to read the <c>load_torque</c> register value.
        /// Torque required to produce the rated power of an each electrical motor at load speed., _: kg/cm
        /// </summary>
        bool TryGetLoadTorque(out float value)
        {
            object[] values;
            if (this.TryGetRegisterValues((ushort)DualMotorsReg.LoadTorque, DualMotorsRegPack.LoadTorque, out values)) 
            {
                value = (float)values[0];
                return true;
            }
            else
            {
                value = default(float);
                return false;
            }
        }

        /// <summary>
        /// Tries to read the <c>load_rotation_speed</c> register value.
        /// Revolutions per minute of the motor under full load., _: rpm
        /// </summary>
        bool TryGetLoadRotationSpeed(out float value)
        {
            object[] values;
            if (this.TryGetRegisterValues((ushort)DualMotorsReg.LoadRotationSpeed, DualMotorsRegPack.LoadRotationSpeed, out values)) 
            {
                value = (float)values[0];
                return true;
            }
            else
            {
                value = default(float);
                return false;
            }
        }

        /// <summary>
        /// Tries to read the <c>reversible</c> register value.
        /// Indicates if the motors can run backwards., 
        /// </summary>
        bool TryGetReversible(out bool value)
        {
            object[] values;
            if (this.TryGetRegisterValues((ushort)DualMotorsReg.Reversible, DualMotorsRegPack.Reversible, out values)) 
            {
                value = (bool)values[0];
                return true;
            }
            else
            {
                value = default(bool);
                return false;
            }
        }


    }
}