/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients 
{
    /// <summary>
    /// Controls a HID joystick.
    /// Implements a client for the HID Joystick service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/hidjoystick/" />
    public partial class HidJoystickClient : Client
    {
        public HidJoystickClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.HidJoystick)
        {
        }

        /// <summary>
        /// Reads the <c>button_count</c> register value.
        /// Number of button report supported, 
        /// </summary>
        public uint ButtonCount
        {
            get
            {
                return (uint)this.GetRegisterValue((ushort)HidJoystickReg.ButtonCount, HidJoystickRegPack.ButtonCount);
            }
        }

        /// <summary>
        /// Reads the <c>buttons_analog</c> register value.
        /// A bitset that indicates which button is analog., 
        /// </summary>
        public uint ButtonsAnalog
        {
            get
            {
                return (uint)this.GetRegisterValue((ushort)HidJoystickReg.ButtonsAnalog, HidJoystickRegPack.ButtonsAnalog);
            }
        }

        /// <summary>
        /// Reads the <c>axis_count</c> register value.
        /// Number of analog input supported, 
        /// </summary>
        public uint AxisCount
        {
            get
            {
                return (uint)this.GetRegisterValue((ushort)HidJoystickReg.AxisCount, HidJoystickRegPack.AxisCount);
            }
        }


    }
}