/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac {

    /// <summary>
    /// A sensor measuring humidity of outside environment.
    /// Implements a client for the Humidity service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/humidity/" />
    public partial class HumidityClient : SensorClient
    {
        public HumidityClient(JDBus bus, string name)
            : base(bus, ServiceClasses.Humidity, name)
        {
        }

        /// <summary>
        /// The relative humidity in percentage of full water saturation., _: %RH
        /// </summary>
        public float Humidity
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)HumidityReg.Humidity, HumidityRegPack.Humidity, 1);
            }
        }

        /// <summary>
        /// (Optional) The real humidity is between `humidity - humidity_error` and `humidity + humidity_error`., _: %RH
        /// </summary>
        public float HumidityError
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)HumidityReg.HumidityError, HumidityRegPack.HumidityError, 1);
            }
        }

        /// <summary>
        /// Lowest humidity that can be reported., _: %RH
        /// </summary>
        public float MinHumidity
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)HumidityReg.MinHumidity, HumidityRegPack.MinHumidity, 1);
            }
        }

        /// <summary>
        /// Highest humidity that can be reported., _: %RH
        /// </summary>
        public float MaxHumidity
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)HumidityReg.MaxHumidity, HumidityRegPack.MaxHumidity, 1);
            }
        }


    }
}