/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients {

    /// <summary>
    /// A light bulb controller.
    /// Implements a client for the Light bulb service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/lightbulb/" />
    public partial class LightBulbClient : Client
    {
        public LightBulbClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.LightBulb)
        {
        }

        /// <summary>
        /// Reads the <c>brightness</c> register value.
        /// Indicates the brightness of the light bulb. Zero means completely off and 0xffff means completely on.
        /// For non-dimmable lights, the value should be clamp to 0xffff for any non-zero value., _: /
        /// </summary>
        public float Brightness
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)LightBulbReg.Brightness, LightBulbRegPack.Brightness);
            }
            set
            {
                
                this.SetRegisterValue((ushort)LightBulbReg.Brightness, LightBulbRegPack.Brightness, value);
            }

        }

        /// <summary>
        /// Tries to read the <c>dimmable</c> register value.
        /// Indicates if the light supports dimming., 
        /// </summary>
        bool TryGetDimmable(out bool values)
        {
            object[] values;
            if (this.TryGetRegisterValues((ushort)LightBulbReg.Dimmable, LightBulbRegPack.Dimmable, out value)) 
            {
                value = (bool)values[0];
                return true;
            }
            else
            {
                value = default(bool);
                return false;
            }
        }


    }
}