/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients 
{
    /// <summary>
    /// Send various events to PC, including opening a URL, start an app, sending text, etc.
    /// Implements a client for the PC controller service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/pccontroller/" />
    public partial class PCControllerClient : Client
    {
        public PCControllerClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.PCController)
        {
        }


        
        /// <summary>
        /// Open a URL in the default browser.
        /// </summary>
        public void OpenUrl(string url)
        {
            this.SendCmdPacked((ushort)PCControllerCmd.OpenUrl, PCControllerCmdPack.OpenUrl, new object[] { url });
        }

        
        /// <summary>
        /// Start an app.
        /// </summary>
        public void StartApp(string name)
        {
            this.SendCmdPacked((ushort)PCControllerCmd.StartApp, PCControllerCmdPack.StartApp, new object[] { name });
        }

        
        /// <summary>
        /// Send text to the active window.
        /// </summary>
        public void SendText(string text)
        {
            this.SendCmdPacked((ushort)PCControllerCmd.SendText, PCControllerCmdPack.SendText, new object[] { text });
        }

        
        /// <summary>
        /// Run a script.
        /// </summary>
        public void RunScript(string script)
        {
            this.SendCmdPacked((ushort)PCControllerCmd.RunScript, PCControllerCmdPack.RunScript, new object[] { script });
        }

    }
}