/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac {

    /// <summary>
    /// A slider or rotary potentiometer.
    /// Implements a client for the Potentiometer service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/potentiometer/" />
    public partial class PotentiometerClient : SensorClient
    {
        public PotentiometerClient(JDBus bus, string name)
            : base(bus, ServiceClasses.Potentiometer, name)
        {
        }

        /// <summary>
        /// The relative position of the slider., _: /
        /// </summary>
        public float Position
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)PotentiometerReg.Position, PotentiometerRegPack.Position, 100);
            }
        }

        /// <summary>
        /// (Optional) Specifies the physical layout of the potentiometer., 
        /// </summary>
        public PotentiometerVariant Variant
        {
            get
            {
                return (PotentiometerVariant)this.GetRegisterValue((ushort)PotentiometerReg.Variant, PotentiometerRegPack.Variant, 1);
            }
        }


    }
}