/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac {

    /// <summary>
    /// A sensor approximating the oxygen level.
     /// 
     /// **Jacdac is not suitable for medical devices and should NOT be used in any kind of device to diagnose or treat any medical conditions.**
    /// Implements a client for the Pulse Oximeter service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/pulseoximeter/" />
    public partial class PulseOximeterClient : SensorClient
    {
        public PulseOximeterClient(JDBus bus, string name)
            : base(bus, ServiceClasses.PulseOximeter, name)
        {
        }

        /// <summary>
        /// The estimated oxygen level in blood., _: %
        /// </summary>
        public float Oxygen
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)PulseOximeterReg.Oxygen, PulseOximeterRegPack.Oxygen, 1);
            }
        }

        /// <summary>
        /// (Optional) The estimated error on the reported sensor data., _: %
        /// </summary>
        public float OxygenError
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)PulseOximeterReg.OxygenError, PulseOximeterRegPack.OxygenError, 1);
            }
        }


    }
}