/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients {

    /// <summary>
    /// Measures the amount of liquid precipitation over an area in a predefined period of time.
    /// Implements a client for the Rain gauge service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/raingauge/" />
    public partial class RainGaugeClient : SensorClient
    {
        public RainGaugeClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.RainGauge)
        {
        }

        /// <summary>
        /// Total precipitation recorded so far., _: mm
        /// </summary>
        public float Precipitation
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)RainGaugeReg.Precipitation, RainGaugeRegPack.Precipitation);
            }
        }

        /// <summary>
        /// (Optional) Typically the amount of rain needed for tipping the bucket., _: mm
        /// </summary>
        public float PrecipitationPrecision
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)RainGaugeReg.PrecipitationPrecision, RainGaugeRegPack.PrecipitationPrecision);
            }
        }


    }
}