/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients {

    /// <summary>
    /// A switching relay.
     /// 
     /// The contacts should be labelled `NO` (normally open), `COM` (common), and `NC` (normally closed).
     /// When relay is energized it connects `NO` and `COM`.
     /// When relay is not energized it connects `NC` and `COM`.
     /// Some relays may be missing `NO` or `NC` contacts.
     /// When relay module is not powered, or is in bootloader mode, it is not energized (connects `NC` and `COM`).
    /// Implements a client for the Relay service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/relay/" />
    public partial class RelayClient : Client
    {
        public RelayClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.Relay)
        {
        }

        /// <summary>
        /// Indicates whether the relay circuit is currently energized or not., 
        /// </summary>
        public bool Active
        {
            get
            {
                return (bool)this.GetRegisterValue((ushort)RelayReg.Active, RelayRegPack.Active);
            }
            set
            {
                
                this.SetRegisterValue((ushort)RelayReg.Active, RelayRegPack.Active, value);
            }

        }

        /// <summary>
        /// (Optional) Describes the type of relay used., 
        /// </summary>
        public RelayVariant Variant
        {
            get
            {
                return (RelayVariant)this.GetRegisterValue((ushort)RelayReg.Variant, RelayRegPack.Variant);
            }
        }

        /// <summary>
        /// (Optional) Maximum switching current for a resistive load., _: mA
        /// </summary>
        public uint MaxSwitchingCurrent
        {
            get
            {
                return (uint)this.GetRegisterValue((ushort)RelayReg.MaxSwitchingCurrent, RelayRegPack.MaxSwitchingCurrent);
            }
        }


    }
}