/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac {

    /// <summary>
    /// A soil moisture sensor.
    /// Implements a client for the Soil moisture service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/soilmoisture/" />
    public partial class SoilMoistureClient : SensorClient
    {
        public SoilMoistureClient(JDBus bus, string name)
            : base(bus, ServiceClasses.SoilMoisture, name)
        {
        }

        /// <summary>
        /// Indicates the wetness of the soil, from `dry` to `wet`., _: /
        /// </summary>
        public float Moisture
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)SoilMoistureReg.Moisture, SoilMoistureRegPack.Moisture, 100);
            }
        }

        /// <summary>
        /// (Optional) The error on the moisture reading., _: /
        /// </summary>
        public float MoistureError
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)SoilMoistureReg.MoistureError, SoilMoistureRegPack.MoistureError, 100);
            }
        }

        /// <summary>
        /// (Optional) Describe the type of physical sensor., 
        /// </summary>
        public SoilMoistureVariant Variant
        {
            get
            {
                return (SoilMoistureVariant)this.GetRegisterValue((ushort)SoilMoistureReg.Variant, SoilMoistureRegPack.Variant, 1);
            }
        }


    }
}