/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients 
{
    /// <summary>
    /// A sound level detector sensor, gives a relative indication of the sound level.
    /// Implements a client for the Sound level service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/soundlevel/" />
    public partial class SoundLevelClient : SensorClient
    {
        public SoundLevelClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.SoundLevel)
        {
        }

        /// <summary>
        /// Reads the <c>sound_level</c> register value.
        /// The sound level detected by the microphone, _: /
        /// </summary>
        public float SoundLevel
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)SoundLevelReg.SoundLevel, SoundLevelRegPack.SoundLevel);
            }
        }

        /// <summary>
        /// Reads the <c>enabled</c> register value.
        /// Turn on or off the microphone., 
        /// </summary>
        public bool Enabled
        {
            get
            {
                return (bool)this.GetRegisterValueAsBool((ushort)SoundLevelReg.Enabled, SoundLevelRegPack.Enabled);
            }
            set
            {
                
                this.SetRegisterValue((ushort)SoundLevelReg.Enabled, SoundLevelRegPack.Enabled, value);
            }

        }

        /// <summary>
        /// Tries to read the <c>loud_threshold</c> register value.
        /// The sound level to trigger a loud event., _: /
        /// </summary>
        bool TryGetLoudThreshold(out float value)
        {
            object[] values;
            if (this.TryGetRegisterValues((ushort)SoundLevelReg.LoudThreshold, SoundLevelRegPack.LoudThreshold, out values)) 
            {
                value = (float)values[0];
                return true;
            }
            else
            {
                value = default(float);
                return false;
            }
        }
        
        /// <summary>
        /// Sets the loud_threshold value
        /// </summary>
        public void SetLoudThreshold(float value)
        {
            this.SetRegisterValue((ushort)SoundLevelReg.LoudThreshold, SoundLevelRegPack.LoudThreshold, value);
        }


        /// <summary>
        /// Raised when a loud sound is detected
        /// </summary>
        public event ClientEventHandler Loud
        {
            add
            {
                this.AddEvent((ushort)SoundLevelEvent.Loud, value);
            }
            remove
            {
                this.RemoveEvent((ushort)SoundLevelEvent.Loud, value);
            }
        }


    }
}