/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac {

    /// <summary>
    /// A microphone that analyzes the sound specturm
    /// Implements a client for the Sound Spectrum service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/soundspectrum/" />
    public partial class SoundSpectrumClient : SensorClient
    {
        public SoundSpectrumClient(JDBus bus, string name)
            : base(bus, (ushort)SoundSpectrumConstants.ServiceClass, name)
        {
        }

        /// <summary>
        /// The computed frequency data., 
        /// </summary>
        public byte[] FrequencyBins
        {
            get
            {
                return (byte[])this.GetRegisterValue((ushort)SoundSpectrumReg.FrequencyBins, SoundSpectrumRegPack.FrequencyBins, 1);
            }
        }

        /// <summary>
        /// Turns on/off the micropohone., 
        /// </summary>
        public bool Enabled
        {
            get
            {
                return (bool)this.GetRegisterValue((ushort)SoundSpectrumReg.Enabled, SoundSpectrumRegPack.Enabled, 1);
            }
            set
            {
                
                this.SetRegisterValue((ushort)SoundSpectrumReg.Enabled, SoundSpectrumRegPack.Enabled, 1, value);
            }

        }

        /// <summary>
        /// The power of 2 used as the size of the FFT to be used to determine the frequency domain., 
        /// </summary>
        public uint FftPow2Size
        {
            get
            {
                return (uint)this.GetRegisterValue((ushort)SoundSpectrumReg.FftPow2Size, SoundSpectrumRegPack.FftPow2Size, 1);
            }
            set
            {
                
                this.SetRegisterValue((ushort)SoundSpectrumReg.FftPow2Size, SoundSpectrumRegPack.FftPow2Size, 1, value);
            }

        }

        /// <summary>
        /// The minimum power value in the scaling range for the FFT analysis data, _: dB
        /// </summary>
        public int MinDecibels
        {
            get
            {
                return (int)this.GetRegisterValue((ushort)SoundSpectrumReg.MinDecibels, SoundSpectrumRegPack.MinDecibels, 1);
            }
            set
            {
                
                this.SetRegisterValue((ushort)SoundSpectrumReg.MinDecibels, SoundSpectrumRegPack.MinDecibels, 1, value);
            }

        }

        /// <summary>
        /// The maximum power value in the scaling range for the FFT analysis data, _: dB
        /// </summary>
        public int MaxDecibels
        {
            get
            {
                return (int)this.GetRegisterValue((ushort)SoundSpectrumReg.MaxDecibels, SoundSpectrumRegPack.MaxDecibels, 1);
            }
            set
            {
                
                this.SetRegisterValue((ushort)SoundSpectrumReg.MaxDecibels, SoundSpectrumRegPack.MaxDecibels, 1, value);
            }

        }

        /// <summary>
        /// The averaging constant with the last analysis frame.
        /// If `0` is set, there is no averaging done, whereas a value of `1` means "overlap the previous and current buffer quite a lot while computing the value"., _: /
        /// </summary>
        public float SmoothingTimeConstant
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)SoundSpectrumReg.SmoothingTimeConstant, SoundSpectrumRegPack.SmoothingTimeConstant, 100);
            }
            set
            {
                
                this.SetRegisterValue((ushort)SoundSpectrumReg.SmoothingTimeConstant, SoundSpectrumRegPack.SmoothingTimeConstant, 100, value);
            }

        }


    }
}