/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients 
{
    /// <summary>
    /// A sound level detector sensor, gives a relative indication of the sound level.
    /// Implements a client for the Sound level service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/soundlevel/" />
    public partial class SoundLevelClient : SensorClient
    {
        public SoundLevelClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.SoundLevel)
        {
        }

        /// <summary>
        /// Reads the <c>sound_level</c> register value.
        /// The sound level detected by the microphone, _: /
        /// </summary>
        public float SoundLevel
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)SoundLevelReg.SoundLevel, SoundLevelRegPack.SoundLevel);
            }
        }

        /// <summary>
        /// Reads the <c>enabled</c> register value.
        /// Turn on or off the microphone., 
        /// </summary>
        public bool Enabled
        {
            get
            {
                return (bool)this.GetRegisterValueAsBool((ushort)SoundLevelReg.Enabled, SoundLevelRegPack.Enabled);
            }
            set
            {
                
                this.SetRegisterValue((ushort)SoundLevelReg.Enabled, SoundLevelRegPack.Enabled, value);
            }

        }


    }
}