/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients {

    /// <summary>
    /// A switch, which keeps its position.
    /// Implements a client for the Switch service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/switch/" />
    public partial class SwitchClient : SensorClient
    {
        public SwitchClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.Switch)
        {
        }

        /// <summary>
        /// Indicates whether the switch is currently active (on)., 
        /// </summary>
        public bool Active
        {
            get
            {
                return (bool)this.GetRegisterValue((ushort)SwitchReg.Active, SwitchRegPack.Active);
            }
        }

        /// <summary>
        /// (Optional) Describes the type of switch used., 
        /// </summary>
        public SwitchVariant Variant
        {
            get
            {
                return (SwitchVariant)this.GetRegisterValue((ushort)SwitchReg.Variant, SwitchRegPack.Variant);
            }
        }

        /// <summary>
        /// (Optional) Specifies the delay without activity to automatically turn off after turning on.
        /// For example, some light switches in staircases have such a capability., _: s
        /// </summary>
        public float AutoOffDelay
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)SwitchReg.AutoOffDelay, SwitchRegPack.AutoOffDelay);
            }
        }

        /// <summary>
        /// Emitted when switch goes from `off` to `on`.
        /// </summary>
        public event ClientEventHandler On
        {
            add
            {
                this.AddEvent((ushort)SwitchEvent.On, value);
            }
            remove
            {
                this.RemoveEvent((ushort)SwitchEvent.On, value);
            }
        }

        /// <summary>
        /// Emitted when switch goes from `on` to `off`.
        /// </summary>
        public event ClientEventHandler Off
        {
            add
            {
                this.AddEvent((ushort)SwitchEvent.Off, value);
            }
            remove
            {
                this.RemoveEvent((ushort)SwitchEvent.Off, value);
            }
        }


    }
}