/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac {

    /// <summary>
    /// Data transfer over TCP/IP and TLS stream sockets.
    /// Implements a client for the TCP service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/tcp/" />
    public partial class TcpClient : Client
    {
        public TcpClient(JDBus bus, string name)
            : base(bus, ServiceClasses.Tcp, name)
        {
        }


    }
}