/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients {

    /// <summary>
    /// Measures equivalent Total Volatile Organic Compound levels.
    /// Implements a client for the Total Volatile organic compound service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/tvoc/" />
    public partial class TvocClient : SensorClient
    {
        public TvocClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.Tvoc)
        {
        }

        /// <summary>
        /// Reads the <c>TVOC</c> register value.
        /// Total volatile organic compound readings in parts per billion., _: ppb
        /// </summary>
        public float TVOC
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)TvocReg.TVOC, TvocRegPack.TVOC);
            }
        }

        /// <summary>
        /// Tries to read the <c>TVOC_error</c> register value.
        /// Error on the reading data, _: ppb
        /// </summary>
        bool TryGetTVOCError(out float value)
        {
            object[] values;
            if (this.TryGetRegisterValues((ushort)TvocReg.TVOCError, TvocRegPack.TVOCError, out values)) 
            {
                value = (float)values[0];
                return true;
            }
            else
            {
                value = default(float);
                return false;
            }
        }

        /// <summary>
        /// Reads the <c>min_TVOC</c> register value.
        /// Minimum measurable value, _: ppb
        /// </summary>
        public float MinTVOC
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)TvocReg.MinTVOC, TvocRegPack.MinTVOC);
            }
        }

        /// <summary>
        /// Reads the <c>max_TVOC</c> register value.
        /// Minimum measurable value., _: ppb
        /// </summary>
        public float MaxTVOC
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)TvocReg.MaxTVOC, TvocRegPack.MaxTVOC);
            }
        }


    }
}