/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients {

    /// <summary>
    /// Measures equivalent Total Volatile Organic Compound levels.
    /// Implements a client for the Total Volatile organic compound service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/tvoc/" />
    public partial class TvocClient : SensorClient
    {
        public TvocClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.Tvoc)
        {
        }

        /// <summary>
        /// Total volatile organic compound readings in parts per billion., _: ppb
        /// </summary>
        public float TVOC
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)TvocReg.TVOC, TvocRegPack.TVOC);
            }
        }

        /// <summary>
        /// (Optional) Error on the reading data, _: ppb
        /// </summary>
        public float TVOCError
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)TvocReg.TVOCError, TvocRegPack.TVOCError);
            }
        }

        /// <summary>
        /// Minimum measurable value, _: ppb
        /// </summary>
        public float MinTVOC
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)TvocReg.MinTVOC, TvocRegPack.MinTVOC);
            }
        }

        /// <summary>
        /// Minimum measurable value., _: ppb
        /// </summary>
        public float MaxTVOC
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)TvocReg.MaxTVOC, TvocRegPack.MaxTVOC);
            }
        }


    }
}