/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac {

    /// <summary>
    /// A mixin service that exposes verified telemetry information for a sensor (see https://github.com/Azure/Verified-Telemetry/tree/main/PnPModel).
    /// Implements a client for the Verified Telemetry service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/verifiedtelemetrysensor/" />
    public partial class VerifiedTelemetryClient : Client
    {
        public VerifiedTelemetryClient(JDBus bus, string name)
            : base(bus, (ushort)VerifiedTelemetryConstants.ServiceClass, name)
        {
        }

        /// <summary>
        /// Reads the telemetry working status, where ``true`` is working and ``false`` is faulty., 
        /// </summary>
        public VerifiedTelemetryStatus TelemetryStatus
        {
            get
            {
                return (VerifiedTelemetryStatus)this.GetRegisterValue((ushort)VerifiedTelemetryReg.TelemetryStatus, VerifiedTelemetryRegPack.TelemetryStatus, 1);
            }
        }

        /// <summary>
        /// (Optional) Specifies the interval between computing the fingerprint information., _: ms
        /// </summary>
        public uint TelemetryStatusInterval
        {
            get
            {
                return (uint)this.GetRegisterValue((ushort)VerifiedTelemetryReg.TelemetryStatusInterval, VerifiedTelemetryRegPack.TelemetryStatusInterval, 1);
            }
            set
            {
                
                this.SetRegisterValue((ushort)VerifiedTelemetryReg.TelemetryStatusInterval, VerifiedTelemetryRegPack.TelemetryStatusInterval, 1, value);
            }

        }

        /// <summary>
        /// Type of the fingerprint., 
        /// </summary>
        public VerifiedTelemetryFingerprintType FingerprintType
        {
            get
            {
                return (VerifiedTelemetryFingerprintType)this.GetRegisterValue((ushort)VerifiedTelemetryReg.FingerprintType, VerifiedTelemetryRegPack.FingerprintType, 1);
            }
        }

        /// <summary>
        /// Template Fingerprint information of a working sensor., confidence: %
        /// </summary>
        public (uint, byte[]) FingerprintTemplate
        {
            get
            {
                return ((uint, byte[]))this.GetRegisterValue((ushort)VerifiedTelemetryReg.FingerprintTemplate, VerifiedTelemetryRegPack.FingerprintTemplate, 1);
            }
        }

        /// <summary>
        /// The telemetry status of the device was updated.
        /// </summary>
        public event NodeEventHandler TelemetryStatusChange;

        /// <summary>
        /// The fingerprint template was updated
        /// </summary>
        public event NodeEventHandler FingerprintTemplateChange;


        /// <summary>
        /// This command will clear the template fingerprint of a sensor and collect a new template fingerprint of the attached sensor.
        /// </summary>
        public void ResetFingerprintTemplate()
        {
            this.SendCmdPacked((ushort)VerifiedTelemetryCmd.ResetFingerprintTemplate, VerifiedTelemetryCmdPack.ResetFingerprintTemplate, new object[] {  });
        }

        /// <summary>
        /// This command will append a new template fingerprint to the `fingerprintTemplate`. Appending more fingerprints will increase the accuracy in detecting the telemetry status.
        /// </summary>
        public void RetrainFingerprintTemplate()
        {
            this.SendCmdPacked((ushort)VerifiedTelemetryCmd.RetrainFingerprintTemplate, VerifiedTelemetryCmdPack.RetrainFingerprintTemplate, new object[] {  });
        }

    }
}