/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients {

    /// <summary>
    /// A vibration motor.
    /// Implements a client for the Vibration motor service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/vibrationmotor/" />
    public partial class VibrationMotorClient : Client
    {
        public VibrationMotorClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.VibrationMotor)
        {
        }


    }
}