/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac {

    /// <summary>
    /// A sensor that measures liquid/water level.
    /// Implements a client for the Water level service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/waterlevel/" />
    public partial class WaterLevelClient : SensorClient
    {
        public WaterLevelClient(JDBus bus, string name)
            : base(bus, (ushort)WaterLevelConstants.ServiceClass, name)
        {
        }

        /// <summary>
        /// The reported water level., _: /
        /// </summary>
        public float Level
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)WaterLevelReg.Level, WaterLevelRegPack.Level, 100);
            }
        }

        /// <summary>
        /// (Optional) The error rage on the current reading, _: /
        /// </summary>
        public float LevelError
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)WaterLevelReg.LevelError, WaterLevelRegPack.LevelError, 100);
            }
        }

        /// <summary>
        /// (Optional) The type of physical sensor., 
        /// </summary>
        public WaterLevelVariant Variant
        {
            get
            {
                return (WaterLevelVariant)this.GetRegisterValue((ushort)WaterLevelReg.Variant, WaterLevelRegPack.Variant, 1);
            }
        }


    }
}