/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac {

    /// <summary>
    /// A sensor that measures wind speed.
    /// Implements a client for the Wind speed service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/windspeed/" />
    public partial class WindSpeedClient : SensorClient
    {
        public WindSpeedClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.WindSpeed)
        {
        }

        /// <summary>
        /// The velocity of the wind., _: m/s
        /// </summary>
        public float WindSpeed
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)WindSpeedReg.WindSpeed, WindSpeedRegPack.WindSpeed);
            }
        }

        /// <summary>
        /// (Optional) Error on the reading, _: m/s
        /// </summary>
        public float WindSpeedError
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)WindSpeedReg.WindSpeedError, WindSpeedRegPack.WindSpeedError);
            }
        }

        /// <summary>
        /// (Optional) Maximum speed that can be measured by the sensor., _: m/s
        /// </summary>
        public float MaxWindSpeed
        {
            get
            {
                return (float)this.GetRegisterValue((ushort)WindSpeedReg.MaxWindSpeed, WindSpeedRegPack.MaxWindSpeed);
            }
        }


    }
}