/** Autogenerated file. Do not edit. */
using Jacdac;
using System;

namespace Jacdac.Clients {

    /// <summary>
    /// A sensor that measures wind direction.
    /// Implements a client for the Wind direction service.
    /// </summary>
    /// <seealso cref="https://microsoft.github.io/jacdac-docs/services/winddirection/" />
    public partial class WindDirectionClient : SensorClient
    {
        public WindDirectionClient(JDBus bus, string name)
            : base(bus, name, ServiceClasses.WindDirection)
        {
        }

        /// <summary>
        /// The direction of the wind., _: °
        /// </summary>
        public uint WindDirection
        {
            get
            {
                return (uint)this.GetRegisterValue((ushort)WindDirectionReg.WindDirection, WindDirectionRegPack.WindDirection);
            }
        }

        /// <summary>
        /// (Optional) Error on the wind direction reading, _: °
        /// </summary>
        public uint WindDirectionError
        {
            get
            {
                return (uint)this.GetRegisterValue((ushort)WindDirectionReg.WindDirectionError, WindDirectionRegPack.WindDirectionError);
            }
        }


    }
}