namespace Jacdac {
    public static partial class ServiceClasses
    {
        public const uint DeviceScriptManager = 0x1134ea2b;
    }

    public enum DeviceScriptManagerMessageFlags: byte { // uint8_t
        ToBeContinued = 0x1,
    }

    public enum DeviceScriptManagerCmd : ushort {
        /// <summary>
        /// Argument: bytecode_size B uint32_t. Open pipe for streaming in the bytecode of the program. The size of the bytecode has to be declared upfront.
        /// To clear the program, use `bytecode_size == 0`.
        /// The bytecode is streamed over regular pipe data packets.
        /// The bytecode shall be fully written into flash upon closing the pipe.
        /// If `autostart` is true, the program will start after being deployed.
        /// The data payloads, including the last one, should have a size that is a multiple of 32 bytes.
        /// Thus, the initial bytecode_size also needs to be a multiple of 32.
        ///
        /// ```
        /// const [bytecodeSize] = jdunpack<[number]>(buf, "u32")
        /// ```
        /// </summary>
        DeployBytecode = 0x80,

        /// <summary>
        /// report DeployBytecode
        /// ```
        /// const [bytecodePort] = jdunpack<[number]>(buf, "u16")
        /// ```
        /// </summary>

        /// <summary>
        /// Argument: bytecode pipe (bytes). Get the current bytecode deployed on device.
        ///
        /// ```
        /// const [bytecode] = jdunpack<[Uint8Array]>(buf, "b[12]")
        /// ```
        /// </summary>
        ReadBytecode = 0x81,

        /// <summary>
        /// Generated by `console.log()` calls from DeviceScript program.
        /// The counter starts at `0`, increments by `1` for each packet and wraps around.
        /// It can be used to detect if some messages are missing.
        /// If message is too long to fit in a single packet, it will be fragmented (this is not implemented yet).
        /// In a fragmented message, all packets except for the last one have `ToBeContinued` flag set.
        /// Note that `counter` field will increase in each fragment.
        /// `log_message` reports are only sent when `logging == true`.
        ///
        /// ```
        /// const [counter, flags, message] = jdunpack<[number, DeviceScriptManagerMessageFlags, string]>(buf, "u8 u8 s")
        /// ```
        /// </summary>
        LogMessage = 0x82,
    }

    public static class DeviceScriptManagerCmdPack {
        /// <summary>
        /// Pack format for 'deploy_bytecode' register data.
        /// </summary>
        public const string DeployBytecode = "u32";

        /// <summary>
        /// Pack format for 'deploy_bytecode' register data.
        /// </summary>
        public const string DeployBytecodeReport = "u16";

        /// <summary>
        /// Pack format for 'read_bytecode' register data.
        /// </summary>
        public const string ReadBytecode = "b[12]";

        /// <summary>
        /// Pack format for 'log_message' register data.
        /// </summary>
        public const string LogMessage = "u8 u8 s";
    }


    /// <summary>
    /// pipe_report Bytecode
    /// ```
    /// const [data] = jdunpack<[Uint8Array]>(buf, "b")
    /// ```
    /// </summary>


    public static class DeviceScriptManagerinfoPack {
        /// <summary>
        /// Pack format for 'bytecode' register data.
        /// </summary>
        public const string Bytecode = "b";
    }

    public enum DeviceScriptManagerReg : ushort {
        /// <summary>
        /// Read-write bool (uint8_t). Indicates if the program is currently running.
        /// To restart the program, stop it (write `0`), read back the register to make sure it's stopped,
        /// start it, and read back.
        ///
        /// ```
        /// const [running] = jdunpack<[number]>(buf, "u8")
        /// ```
        /// </summary>
        Running = 0x80,

        /// <summary>
        /// Read-write bool (uint8_t). Indicates wheather the program should be re-started upon `reboot()` or `panic()`.
        /// Defaults to `true`.
        ///
        /// ```
        /// const [autostart] = jdunpack<[number]>(buf, "u8")
        /// ```
        /// </summary>
        Autostart = 0x81,

        /// <summary>
        /// Read-write bool (uint8_t). `log_message` reports are only sent when this is `true`.
        /// It defaults to `false`.
        ///
        /// ```
        /// const [logging] = jdunpack<[number]>(buf, "u8")
        /// ```
        /// </summary>
        Logging = 0x82,

        /// <summary>
        /// Read-only uint32_t. The size of current program.
        ///
        /// ```
        /// const [programSize] = jdunpack<[number]>(buf, "u32")
        /// ```
        /// </summary>
        ProgramSize = 0x180,

        /// <summary>
        /// Read-only uint32_t. Return FNV1A hash of the current bytecode.
        ///
        /// ```
        /// const [programHash] = jdunpack<[number]>(buf, "u32")
        /// ```
        /// </summary>
        ProgramHash = 0x181,

        /// <summary>
        /// Read-only bytes. Return 32-byte long SHA-256 hash of the current bytecode.
        ///
        /// ```
        /// const [programSha256] = jdunpack<[Uint8Array]>(buf, "b[32]")
        /// ```
        /// </summary>
        ProgramSha256 = 0x182,
    }

    public static class DeviceScriptManagerRegPack {
        /// <summary>
        /// Pack format for 'running' register data.
        /// </summary>
        public const string Running = "u8";

        /// <summary>
        /// Pack format for 'autostart' register data.
        /// </summary>
        public const string Autostart = "u8";

        /// <summary>
        /// Pack format for 'logging' register data.
        /// </summary>
        public const string Logging = "u8";

        /// <summary>
        /// Pack format for 'program_size' register data.
        /// </summary>
        public const string ProgramSize = "u32";

        /// <summary>
        /// Pack format for 'program_hash' register data.
        /// </summary>
        public const string ProgramHash = "u32";

        /// <summary>
        /// Pack format for 'program_sha256' register data.
        /// </summary>
        public const string ProgramSha256 = "b[32]";
    }

    public enum DeviceScriptManagerEvent : ushort {
        /// <summary>
        /// Emitted when the program calls `panic(panic_code)` or `reboot()` (`panic_code == 0` in that case).
        /// The byte offset in byte code of the call is given in `program_counter`.
        /// The program will restart immediately when `panic_code == 0` or in a few seconds otherwise.
        ///
        /// ```
        /// const [panicCode, programCounter] = jdunpack<[number, number]>(buf, "u32 u32")
        /// ```
        /// </summary>
        ProgramPanic = 0x80,

        /// <summary>
        /// Emitted after bytecode of the program has changed.
        /// </summary>
        ProgramChange = 0x3,
    }

    public static class DeviceScriptManagerEventPack {
        /// <summary>
        /// Pack format for 'program_panic' register data.
        /// </summary>
        public const string ProgramPanic = "u32 u32";
    }

}
